<Project Sdk="Aspire.AppHost.Sdk/13.0.0">

  <ItemGroup>
    <ProjectReference Include="..\BestBlogs.API\BestBlogs.API.csproj" />
    <ProjectReference Include="..\BestBlogs.ServiceDefaults\BestBlogs.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.NodeJs" Version="9.5.2" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.0.2" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>9ef5d6ca-f7de-4b77-84ee-ce416602bf9d</UserSecretsId>
  </PropertyGroup>

</Project>
